### ISSUE TITLE
xen Todo list

### ISSUE THREAD

**Issue by xen-42** [xen-42/ow-mod-jam-4#1]
- [x] Make coordinate interface puzzle activate once it slots down
- [x] Place keys in layer 1 chests and coordinate interface chest
- [x] Adjust quantum puzzle key position
- [x] Make red scroll actually red
- [x] Disable ship ignition sfx
- [x] immunity to damage
- [x] infinite fuel
- [x] secondary coordinate solution (the existing solution but upside down, then shift them one slot left and wrap around)
- [x] fix the ship log so that the planets are always in a consistent order
- [x] make it so that you can't press up on most fake planets in the map mode except for Fake8
- [x] place final lock
- [x] A MonoBehaviour that I can stick on a Shape that, when the player enters, will make them close their eyes, move to a referenced Transform position, then open their eyes. Going to put this on the water.
- [x] Set up remaining keys
- [x] Door opening sound
- [x] Key socketing sound on locks
- [x] Fix bug that meditation disables all sounds
- [x] Fix Ghost Bird target position staying relative to the player
- [x] Edit the lock placements a bit to look better with the new models

**Comment by GameWyrm** [comment]
Added "Fix Ghost Bird target position staying relative to the player" and "Edit the lock placements a bit to look better with the new models"
